config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', profiles, name='profiles'),
    path('login/', login_user, name='login'),
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
    path('account/', account, name='account'),
    path('account_edit/', account_edit, name='account_edit'),
    path('profiles/<str:id>/', profile, name='profile'),

]

projects/models.py
from django.db import models
import uuid
from users.models import Profil

# Create your models here.
class Project(models.Model):
    user = models.ForeignKey(Profil, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(default='kurik.jpg')
    demo_link = models.CharField(max_length=200, null=True, blank=True)
    source_link = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    vote_count = models.IntegerField(default=0)
    vote_ratio = models.IntegerField(default=0)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    tag = models.ManyToManyField('Tag', blank=True, related_name='project_tag')

    def __str__(self):
        return self.title

class Review(models.Model):
    user = models.ForeignKey(Profil, on_delete=models.SET_NULL, null=True, blank=True)
    VOTE_TYPE = (
        ("+", "Ijobiy"),
        ("-", "Salbiy"),
    )
    body = models.TextField(default='')
    value = models.CharField(max_length=50, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True, related_name='project_review')

    def __str__(self):
        return self.value

class Tag(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name


users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    info = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    social_github = models.CharField(max_length=200, null=True, blank=True)
    social_facebook = models.CharField(max_length=200, null=True, blank=True)
    social_youtube = models.CharField(max_length=200, null=True, blank=True)
    social_instagram = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='profiles', default='profiles/default_profile.webp')
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.user.username)


class Skill(models.Model):
    user = models.ForeignKey(Profil, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)



# Signal.connect(post_save, create_profile, sender=User)
# Signal.connect(post_delete, delete_user, sender=Profil)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Profil

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', "email", 'username', 'password1', 'password2']
        labels = {
            'first_name' : 'Ism',
            'last_name': 'Sharif',
            "email":  "Elektron manzil",
            'username': "Login"
        }

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)

        for key, field in self.fields.items():
            field.widget.attrs.update({'class': 'input input--text'})


class CustomProfilCreationForm(ModelForm):
    class Meta:
        model = Profil
        fields = ['name', 'email', 'info', 'location', 'bio', 'social_github', 'social_facebook', 'social_youtube',
                  'social_instagram',  'image']

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)

        for key, field in self.fields.items():
            field.widget.attrs.update({'class': 'input input--text'})

users/views.py
from django.shortcuts import render, redirect
from .models import Profil
from django.contrib.auth import authenticate, login, logout
from .forms import CustomUserCreationForm, CustomProfilCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def profiles(request):
    users = Profil.objects.all()
    context = {
        'users': users
    }
    return render(request, 'users/profiles.html', context)

def profile(request, id):
    user = Profil.objects.get(id=id)
    context = {
        'user': user
    }
    return render(request, 'users/profile.html', context)


def login_user(request):
    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Tizimga xush kelibsiz')
            return redirect('profiles')
        else:
            messages.error(request, 'Bunday login va parol mavjud emas.')
    return render(request, 'users/login.html')


def logout_user(request):
    logout(request)
    messages.info(request, 'Tizimdan chiqdingiz.')
    return redirect('login')

def register_user(request):
    form = CustomUserCreationForm()
    context = {
        'form': form
    }

    if request.method=='POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            messages.success(request, "Foydalanuvhci ro'yxatdan o'tdi")
            return redirect('profiles')
        else:
            messages.error(request, "Foydalanuvchi ro'yxatdan o'tmadi")
    return render(request, 'users/register.html', context)

@login_required(login_url='login')
def account(request):
    profil = request.user.profil
    context = {
        'profil': profil
    }
    return render(request, 'users/account.html', context)

@login_required(login_url='login')
def account_edit(request):
    profil = request.user.profil
    form = CustomProfilCreationForm(instance=profil)
    if request.method == 'POST':
        form = CustomProfilCreationForm(request.POST, request.FILES, instance=profil)
        if form.is_valid():
            form.save()
            return redirect('account')
    context = {
        'form': form
    }
    return render(request, 'users/account_edit.html', context)

users/templates/users/account.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<body>


  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'account_edit' %}"><i class="im im-edit"></i> O'zgartirish</a>
              <img class="avatar avatar--xl dev__avatar" src="{{ profil.image.url }}" />
              <h2 class="dev__name">{{profil.name}}</h2>
              <p class="dev__title">{{profil.info}}</p>
              <p class="dev__location">{{profil.location}}</p>
              <ul class="dev__social">
                            {% if profil.social_github %}
                            <li>
                                <a title="Github" href="{{profil.social_github}}" target="_blank"><i
                                        class="im im-github"></i></a>
                            </li>
                            {% endif %}
                            {% if user.social_facebook %}
                            <li>
                                <a title="Facebook" href="profil.social_facebook" target="_blank"><i
                                        class="im im-facebook"></i></a>
                            </li>
                            {% endif %}
                            {% if profil.social_youtube %}

                            <li>
                                <a title="Youtube" href="profil.social_youtube" target="_blank"><i
                                        class="im im-youtube"></i></a>
                            </li>
                            {% endif %}
                            {% if profil.social_instagram %}
                            <li>
                                <a title="Instagram" href="profil.social_instagram" target="_blank"><i
                                        class="im im-instagram"></i></a>
                            </li>
                            {% endif %}
                        </ul>
              <a href="#" class="btn btn--sub btn--lg">Habar jo'nating</a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">Men haqimda</h3>
            <p class="devInfo__about">
              {{profil.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Malakalari</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="#"><i class="im im-plus"></i> Malaka
              qo'shish</a>
          </div>

          <table class="settings__table">
            {% for skill in profil.skill_set.all %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{ skill.name }}</h4>
                <p>
                  {{skill.description}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> O'zgartirish</a>
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                  O'chirish</a>
              </td>
            </tr>
            {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Loyihalar</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="#"><i class="im im-plus"></i> Loyiha
              qo'shish</a>
          </div>

          <table class="settings__table">
            {% for project in profil.project_set.all %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'project' project.id %}"><img src="{{project.image.url}}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="single-project.html">{{project.title}}</a>
                <p>
                  {{project.description}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> O'zgartirish</a>
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                  O'chirish</a>
              </td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
</body>

{% endblock content %}

users/templates/users/account_edit.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" action="{% url 'account_edit' %}" method="POST">
                {% csrf_token %}
                <!-- Input:Text -->
                {% for f in form %}
                <div class="form__field">
                    <label for="formInput#text">{{f.label}} </label>
                    {{f}}
                </div>
                {% endfor %}

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Saqlash" />
            </form>
        </div>
    </div>
</main>
{% endblock content %}

users/templates/users/login.html
{% extends 'main.html' %}
{% load static %}

{% block content %}


<div class="auth">
    <div class="card">
        <div class="auth__header text-center">
            <a href="{% url 'profiles' %}">
                <img src="{% static 'images/icon.svg' %}" alt="icon" />
            </a>
            <h3>Shahsiy sahifaga kirish</h3>
            <p>Assalomu alaykum, hush kelibsiz hurmatli dasturchi</p>
        </div>

        <form action="{% url 'login' %}" method="POST" class="form auth__form">
            {% csrf_token %}
            <!-- Input:Email -->
            <div class="form__field">
                <label for="formInput#text">Login: </label>
                <input class="input input--text" id="formInput#text" type="text" name="username"
                    placeholder="Loginni kiriting..." />
            </div>

            <!-- Input:Password -->
            <div class="form__field">
                <label for="formInput#password">Parol: </label>
                <input class="input input--password" id="formInput#passowrd" type="password" name="password"
                    placeholder="Parolni kiriting" />
            </div>
            <div class="auth__actions">
                <input class="btn btn--sub btn--lg" type="submit" value="Kirish" />
                <a href="forgetpassword.html">Parolni unutdingizmi?</a>
            </div>
        </form>
        <div class="auth__alternative">
            <p>Shahsiy sahifangiz yo'qmi?</p>
            <a href="{% url 'register' %}">Ro'yxtdan o'tish</a>
        </div>
    </div>
</div>

{% endblock content %}

users/templates/users/profile.html
{% extends 'main.html' %}

{% block content %}

<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <img class="avatar avatar--xl" src="{{user.image.url}}" />
                        <h2 class="dev__name">{{user}}</h2>
                        <p class="dev__title">{{user.info}}</p>
                        <p class="dev__location">{{user.location}}</p>
                        <ul class="dev__social">
                            {% if user.social_github %}
                            <li>
                                <a title="Github" href="{{user.social_github}}" target="_blank"><i
                                        class="im im-github"></i></a>
                            </li>
                            {% endif %}
                            {% if user.social_facebook %}
                            <li>
                                <a title="Facebook" href="user.social_facebook" target="_blank"><i
                                        class="im im-facebook"></i></a>
                            </li>
                            {% endif %}
                            {% if user.social_youtube %}

                            <li>
                                <a title="Youtube" href="user.social_youtube" target="_blank"><i
                                        class="im im-youtube"></i></a>
                            </li>
                            {% endif %}
                            {% if user.social_instagram %}
                            <li>
                                <a title="Instagram" href="user.social_instagram" target="_blank"><i
                                        class="im im-instagram"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                        <a href="#" class="btn btn--sub btn--lg">Habar jo'nating </a>
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">Men haqimda</h3>
                    <p class="devInfo__about">
                        {{user.bio}}
                    </p>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Malakalari</h3>
                    <div class="devInfo__skills">

                        {% for skill in user.skill_set.all %}
                        <div class="devSkill">
                            <h4 class="devSkill__title">{{skill.name}}</h4>
                            <p class="devSkill__info">
                                {{skill.description}}
                            </p>
                        </div>
                        {% endfor %}


                        <h3 class="devInfo__subtitle">Boshqa malakalar</h3>
                        <div class="devInfo__otherSkills">
                            <span class="tag tag--pill tag--sub tag--lg">
                                <small>HTML</small>
                            </span>
                            <span class="tag tag--pill tag--sub tag--lg">
                                <small>CSS</small>
                            </span>
                            <span class="tag tag--pill tag--sub tag--lg">
                                <small>Bootstrap</small>
                            </span>
                            <span class="tag tag--pill tag--sub tag--lg">
                                <small>Sqlite</small>
                            </span>
                            <span class="tag tag--pill tag--sub tag--lg">
                                <small>Postgres</small>
                            </span>
                            <span class="tag tag--pill tag--sub tag--lg">
                                <small>MongoDB</small>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Loyihalar</h3>
                    <div class="grid grid--two">
                        {% for project in user.project_set.all %}
                        <div class="column">
                            <div class="card project">
                                <a href="single-project.html" class="project">
                                    <img class="project__thumbnail" src="{{project.image.url}}"
                                        alt="project thumbnail" />
                                    <div class="card__body">
                                        <h3 class="project__title">{{project.title}}</h3>
                                        <p><a class="project__author" href="profile.html">{{user}}</a></p>
                                        <p class="project--rating">
                                            <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Ijobiy baho
                                            ({{project.vote_count}} Ovoz)
                                        </p>
                                        <div class="project__tags">
                                            {% for tag in project.tag.all %}
                                            <span class="tag tag--pill tag--main">
                                                <small>{{tag}}</small>
                                            </span>
                                            {% endfor %}

                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}
<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>O'QUV MARKAZ<span> BITIRUVCHILARINI </span> QIDIRIB TOP</h2>

            </div>

            <div class="hero-section__search">
                <form class="form" action="#" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Bitiruvchilarni top </label>
                        <input class="input input--text" id="formInput#search" type="text" name="text"
                            placeholder="Bitiruvchi ismi bilan top" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">
                {% for user in users %}
                <div class="column card">
                    <div class="dev">
                        <a href="{% url 'profile' user.id %}" class="card__body">
                            <div class="dev__profile">
                                <img class="avatar avatar--md" src="" alt="image" />
                                <div class="dev__meta">
                                    <h3>{{user}}</h3>
                                    <h5>{{user.info}}</h5>
                                </div>
                            </div>
                            <p class="dev__info">
                                {{user.bio|slice:":150"}}
                            </p>
                            <div class="dev__skills">
                                {% for skill in user.skill_set.all %}
                                <span class="tag tag--pill tag--main">
                                    <small>{{skill}}</small>
                                </span>
                                {% endfor %}

                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>

    <div class="pagination">
        <ul class="container">
            <li><a href="#" class="btn btn--disabled">&#10094; Orqaga</a></li>
            <li><a href="#" class="btn btn--sub">01</a></li>
            <li><a href="#" class="btn">02</a></li>
            <li><a href="#" class="btn">03</a></li>
            <li><a href="#" class="btn">04</a></li>
            <li><a href="#" class="btn">05</a></li>
            <li><a href="#" class="btn">06</a></li>
            <li><a href="#" class="btn">07</a></li>
            <li><a href="#" class="btn">08</a></li>
            <li><a href="#" class="btn">09</a></li>
            <li><a href="#" class="btn">10</a></li>
            <li><a href="#" class="btn">Oldinga &#10095;</a></li>
        </ul>
    </div>
</main>

{% endblock content %}

users/templates/users/register.html
{% extends 'main.html' %}
{% load static %}


{% block content %}

<div class="auth">
    <div class="card">
        <div class="auth__header text-center">
            <a href="{% url 'profiles' %}">
                <img src="{% static 'images/icon.svg' %}" alt="icon" />
            </a>
            <h3>Account SignUp</h3>
            <p>Create a new developer account</p>
        </div>

        <form action="{% url 'register' %}" method="POST" class="form auth__form">
            {% csrf_token %}
            <!-- Input:Text -->
            {% for f in form %}

            <div class="form__field">
                <label for="formInput#text">{{f.label}} </label>
                {{f}}
            </div>
            {% endfor %}

            <div class="auth__actions">
                <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
            </div>
        </form>
        <div class="auth__alternative">
            <p>Already have an Account?</p>
            <a href="{% url 'login' %}">Log In</a>
        </div>
    </div>
</div>

{% endblock content %}